-- 코드를 입력하세요 
/**
SELECT SALES_DATE,	PRODUCT_ID,	USER_ID	,SALES_AMOUNT
    FROM (SELECT USER_ID	,PRODUCT_ID	,SALES_AMOUNT,	SALES_DATE
    FROM ONLINE_SALE
    UNION ALL
    SELECT NULL AS USER_ID,	PRODUCT_ID,	SALES_AMOUNT,	SALES_DATE
    FROM OFFLINE_SALE) AS A
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID */


SELECT date_format(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE year(SALES_DATE) = 2022 AND month(SALES_DATE) = 3

UNION ALL

SELECT date_format(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE year(SALES_DATE) = 2022 AND month(SALES_DATE) = 3

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID

# SELECT PRODUCT_ID	,SALES_AMOUNT,	SALES_DATE,USER_ID	
#     FROM ONLINE_SALE
#     UNION ALL
#     SELECT PRODUCT_ID,	SALES_AMOUNT,	SALES_DATE , NULL AS USER_ID
#     FROM OFFLINE_SALE
