-- 코드를 입력하세요
SELECT U.USER_ID,	U.NICKNAME,  CONCAT(U.CITY," ",U.STREET_ADDRESS1," ",U.STREET_ADDRESS2) AS 전체주소,
        CONCAT(LEFT(TLNO,3),"-",SUBSTRING(TLNO,4,4),"-",RIGHT(TLNO,4)) 전화번호
FROM USED_GOODS_USER U
JOIN  USED_GOODS_BOARD B ON B.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID
HAVING COUNT(*) >= 3
ORDER BY  U.USER_ID DESC;